data :
  dataset : benchmark
  data_dir : motion_pred_clustbased/data/benchmark_s20 # directory to the folders `eth` `hotel` `univ` `zara1` `zara2`
  dataset_target : eth # specific testing dataset 
  inputs : vect_dir # [options] raw / vect_dir / polar
  output : vect_dir # [options] raw / vect_dir / polar
  skip : 20
  min_ped : 0

clustering :
  algorithm : k-shape # [options] k-means / k-shape / dbscan / hdbscan
  k-means : 
    type : normal # [options] normal / time_series 
    n_clusters : 3
    init : k-means++ # [options] random / k-means++
    metric : softdtw # [options] euclidean / dtw (available for time_series) / softdtw (available for time_series)
    n_init : 10
    max_iter : 300
    n_jobs : -1
    elbow :
      run : True
      min_clusters : 2
      max_clusters : 15
  k-shape : 
    n_clusters : 3
    n_init : 10
    max_iter : 300
    elbow :
      run : True
      min_clusters : 2
      max_clusters : 15
  dbscan : 
    eps : 0.1
    n_jobs : -1
    elbow :
      run : False
      min_samples_ratio : 1
      max_samples_ratio : 3
  hdbscan :
    min_cluster_size : 2
    min_samples : 1
    elbow :
      run : False


save : 
  path : motion_pred_clustbased